"""Initial migration kauth-db

Revision ID: b8352b457691
Revises: 
Create Date: 2026-01-16 22:11:38.095284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8352b457691'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', 'LIFETIME','CUSTOM', name='billingcycle'), nullable=False),
    sa.Column('features', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('rate_limits', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('quota_limits', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active', 'is_verified'], unique=False)
    op.create_index('idx_user_email_active', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_user_phone_active', 'users', ['phone'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apikey_hash_active', 'api_keys', ['key_hash'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_apikey_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('auth_providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('EMAIL', 'WHATSAPP', 'OAUTH2_GOOGLE', name='authprovidertype'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_provider_external', 'auth_providers', ['provider_type', 'provider_user_id'], unique=True)
    op.create_index(op.f('ix_auth_providers_user_id'), 'auth_providers', ['user_id'], unique=False)
    op.create_table('database_transaction_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.Enum('INSERT', 'UPDATE', 'DELETE', name='databaseoperation'), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_db_log_table_time', 'database_transaction_logs', ['table_name', 'created_at'], unique=False)
    op.create_index('idx_db_log_transaction', 'database_transaction_logs', ['transaction_id'], unique=False)
    op.create_table('external_transaction_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_service', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_log_service_time', 'external_transaction_logs', ['external_service', 'created_at'], unique=False)
    op.create_index('idx_external_log_status', 'external_transaction_logs', ['response_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_external_transaction_logs_idempotency_key'), 'external_transaction_logs', ['idempotency_key'], unique=False)
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('delivery_method', sa.Enum('EMAIL', 'WHATSAPP', name='otpdeliverymethod'), nullable=False),
    sa.Column('delivery_target', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTRATION', 'LOGIN', 'PASSWORD_RESET', name='otppurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_target_purpose', 'otp_codes', ['delivery_target', 'purpose'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_table('plan_permissions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'permission_id')
    )
    op.create_table('quotas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('quota_type', sa.String(length=100), nullable=False),
    sa.Column('current_usage', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quota_user_service', 'quotas', ['user_id', 'service_name', 'quota_type'], unique=True)
    op.create_index(op.f('ix_quotas_user_id'), 'quotas', ['user_id'], unique=False)
    op.create_table('service_accesses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allowed_features', sa.JSON(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_access_lookup', 'service_accesses', ['user_id', 'service_name'], unique=False, postgresql_where=sa.text('is_allowed = true'))
    op.create_index(op.f('ix_service_accesses_user_id'), 'service_accesses', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_expiry_active', 'sessions', ['expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_session_user_active', 'sessions', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_behavior_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('geolocation', sa.JSON(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behavior_log_action_time', 'user_behavior_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_behavior_log_user_time', 'user_behavior_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_behavior_logs_action'), 'user_behavior_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_behavior_logs_user_id'), 'user_behavior_logs', ['user_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'EXPIRED', 'CANCELLED', name='userplanstatus'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_userplan_user_active', 'user_plans', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_plans_plan_id'), 'user_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_plans_user_id'), 'user_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_plans_user_id'), table_name='user_plans')
    op.drop_index(op.f('ix_user_plans_plan_id'), table_name='user_plans')
    op.drop_index('idx_userplan_user_active', table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_user_behavior_logs_user_id'), table_name='user_behavior_logs')
    op.drop_index(op.f('ix_user_behavior_logs_action'), table_name='user_behavior_logs')
    op.drop_index('idx_behavior_log_user_time', table_name='user_behavior_logs')
    op.drop_index('idx_behavior_log_action_time', table_name='user_behavior_logs')
    op.drop_table('user_behavior_logs')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index('idx_session_user_active', table_name='sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('idx_session_expiry_active', table_name='sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('sessions')
    op.drop_index(op.f('ix_service_accesses_user_id'), table_name='service_accesses')
    op.drop_index('idx_service_access_lookup', table_name='service_accesses', postgresql_where=sa.text('is_allowed = true'))
    op.drop_table('service_accesses')
    op.drop_index(op.f('ix_quotas_user_id'), table_name='quotas')
    op.drop_index('idx_quota_user_service', table_name='quotas')
    op.drop_table('quotas')
    op.drop_table('plan_permissions')
    op.drop_index('idx_otp_target_purpose', table_name='otp_codes', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_external_transaction_logs_idempotency_key'), table_name='external_transaction_logs')
    op.drop_index('idx_external_log_status', table_name='external_transaction_logs')
    op.drop_index('idx_external_log_service_time', table_name='external_transaction_logs')
    op.drop_table('external_transaction_logs')
    op.drop_index('idx_db_log_transaction', table_name='database_transaction_logs')
    op.drop_index('idx_db_log_table_time', table_name='database_transaction_logs')
    op.drop_table('database_transaction_logs')
    op.drop_index(op.f('ix_auth_providers_user_id'), table_name='auth_providers')
    op.drop_index('idx_auth_provider_external', table_name='auth_providers')
    op.drop_table('auth_providers')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_apikey_user_active', table_name='api_keys')
    op.drop_index('idx_apikey_hash_active', table_name='api_keys', postgresql_where=sa.text('is_active = true'))
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_phone_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_user_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('permissions')
    # ### end Alembic commands ###
